#!/bin/bash
. nsxcall-json

# This script requires a variable called "section"
if [ -z "$section" ]
then
	echo "This script requires a variable called \"section\""
	echo "In case it's not empty, consider using \"export section\""
	exit 1
fi

. /data/nsxv
num_of_rules_v=$(GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules"|jq length)

. /data/nsxt
policy_id=$( GET /policy/api/v1/infra/domains/default/security-policies| jq -r ".results[]|select (.display_name==\"$section\").id" )
num_of_rules_t=$(GET /policy/api/v1/infra/domains/default/security-policies/$policy_id|jq '.rules'|jq length )

if [ $num_of_rules_t -eq $num_of_rules_v ]
then
	echo "\"$section\" NSX-v: $num_of_rules_v NSX-T:  $num_of_rules_t - OK"
else
	difference=$(($num_of_rules_v - $num_of_rules_t))
	echo "\"$section\" NSX-v: $num_of_rules_v NSX-T:  $num_of_rules_t - ${difference#-} differences found"
	if [ $difference -gt 0 ]
	then
		GREEN
		echo $difference rules missing on NSX-T
	else
		RED
		echo ${difference#-} rules missing on NSX-v
	fi
fi
NC
