#!/bin/bash
. nsxcall-json
. /data/nsxt

policy_id=$( GET /policy/api/v1/infra/domains/default/security-policies| jq -r ".results[]|select (.display_name==\"$section\").id" )
[ "$DEBUG" ] && echo "$section"
[ "$DEBUG" ] && echo "    id=$policy_id"
num_of_rules=$(GET /policy/api/v1/infra/domains/default/security-policies/$policy_id|jq '.rules'|jq length )
echo $num_of_rules
