#!/bin/bash
. nsxcall-json
. /data/nsxv

section="SP-EXCEPTION-smr-b2c :: NSX Service Composer - Firewall"
echo "--- \"$section\" ---"
num_of_rules=$(GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules"|jq length)
echo $num_of_rules rules
GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules[].name" | sort

