#!/bin/bash
. nsxcall-json
. /data/nsxt

policy_name="SP-EXCEPTION-smr-b2c :: NSX Service Composer - Firewall"
policy_id=$( GET /policy/api/v1/infra/domains/default/security-policies| jq -r ".results[]|select (.display_name==\"$policy_name\").id" )
echo "policy=$policy_name"
echo "    id=$policy_id"
num_of_rules=$(GET /policy/api/v1/infra/domains/default/security-policies/$policy_id|jq '.rules'|jq length )
echo $num_of_rules rules
#GET /policy/api/v1/infra/domains/default/security-policies|jq 'select(.display_name=="$policy_name").rules[].display_name'
	
#GET /api/4.0/firewall/globalroot-0/config|jq -r '.layer3Sections.layer3Sections[].name' | sort | while read section
#do
#	echo "--- \"$section\" ---"
#	num_of_rules=$(GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules"|jq length)
#	echo $num_of_rules rules
#	GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules[].name" | sort
#done
