#!/bin/bash
. nsxcall-json
. /data/nsxt

#GET /policy/api/v1/infra/domains/default/security-policies
GET /policy/api/v1/infra/domains/default/security-policies|jq -r '.results[].id'| sort | while read policy
do
	echo "--- \"$policy\" ---"
	num_of_rules=$(GET /policy/api/v1/infra/domains/default/security-policies/$policy|jq '.rules'|jq length )
	echo $num_of_rules rules
	GET /policy/api/v1/infra/domains/default/security-policies/$policy|jq '.rules[].display_name'
done
	
#GET /api/4.0/firewall/globalroot-0/config|jq -r '.layer3Sections.layer3Sections[].name' | sort | while read section
#do
#	echo "--- \"$section\" ---"
#	num_of_rules=$(GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules"|jq length)
#	echo $num_of_rules rules
#	GET /api/4.0/firewall/globalroot-0/config|jq ".layer3Sections.layer3Sections[]|select (.name==\"$section\")|.rules[].name" | sort
#done
